const MEBIBYTE = 1024 * 1024;
const GIBIBYTE = 1024 * MEBIBYTE;

export const MAX_SKILL_ARCHIVE_BYTES = 512 * MEBIBYTE;
export const MAX_SKILL_ARCHIVE_EXPANDED_BYTES = GIBIBYTE;
export const MAX_SKILL_ARCHIVE_ENTRY_BYTES = 512 * MEBIBYTE;
export const MAX_SKILL_UPLOAD_REQUEST_BYTES = MAX_SKILL_ARCHIVE_BYTES + 2 * MEBIBYTE;

export const MAX_SKILL_ARCHIVE_LABEL = "512MB";
export const MAX_SKILL_ARCHIVE_EXPANDED_LABEL = "1GB";
